apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../../../base/applications/wordpress

namespace: wordpress

commonLabels:
  app: wordpress


images:
- name: mysql
  newName: harbor.navneetv.com/proxy-cache/library/mysql
  newTag: "8.0"
- name: wordpress
  newName: harbor.navneetv.com/proxy-cache/library/wordpress
  newTag: "6.1.1-php8.1-apache"

secretGenerator:
- name: mysql-pass
  literals:
  - password=Passw0rd!

patches:
- target:
    kind: Certificate
    name: wordpress-cert
  patch: |-
    - op: replace
      path: /spec/commonName
      value: wordpress.sgrhas.io
    - op: replace
      path: /spec/dnsNames/0
      value: wordpress.sgrhas.io
- target:
    kind: HTTPProxy
    name: wordpress
  patch: |-
    - op: replace
      path: /spec/virtualhost/fqdn
      value: wordpress.sgrhas.io