---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: demo-clustergroup-dev-pre-reqs
  namespace: tanzu-continuousdelivery-resources
spec:
  interval: 1m0s
  path: ./environments/demo-clustergroup-prod/pre-reqs
  prune: false
  sourceRef:
    kind: GitRepository
    name: tmc-git-repo
    namespace: tanzu-continuousdelivery-resources
