---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: demo-clustergroup-dev-utilities
  namespace: tanzu-continuousdelivery-resources
spec:
  interval: 1m0s
  path: ./environments/demo-clustergroup-dev/utilities
  prune: true
  sourceRef:
    kind: GitRepository
    name: tmc-git-repo
    namespace: tanzu-continuousdelivery-resources